### ISSUE TITLE
Installation/run instructions

### ISSUE THREAD

**Issue by peterw8102** [ipcortex/FAC-FMC#151]
The readme.md covers some of this but is incomplete.
For example: need information on config.env (format, location, key value pairs etc, default values if any)
Add details to the wiki.

**Comment by RobStallion** [comment]
We can't put the config.env information on the README as it will then be public and we do not want people seeing it's contents. We can send a copy to you privately if you like. We could also mention this in the README if you'd like

**Comment by peterw8102** [comment]
I don't think you need to put up the actual contents. You need to document what the keys are, what the expected values/formats are,  whether a value must be set and if not then what the default value will be.

**Comment by RobStallion** [comment]
Ok, that's no problem. We can add that in. Sorry I misunderstood your first message
