### ISSUE TITLE
filterQueryStringCreator.js

### ISSUE THREAD

**Issue by peterw8102** [ipcortex/FAC-FMC#152]
Quick look at this, which I think is a work in progress?

The code is making use of a sequence of nested callbacks to build up a query string. Unfortunately callbacks are a necessary evil in node's single-threaded async world but they don't make for readable code.

In this case there is no async behaviour that requests callbacks as far as I can see. A more readable form would be something like:

   queryArr = [];
   toAndFromQueryStringCreator(queryArr,obj);
   minAndMaxQueryStringCreator(queryArr,obj);
   dateQueryStringCreator(queryArr,obj)
   untaggedCallsStringCreator(queryArr,obj)
   return queryArr.join(' AND ');

where each of those function pushes a new test onto the queryArr if it has one.

This also simplifies the calling function.

It would also be better to maintain a parameter array and use Postgres $n values rather than encode the parameters into the query string. The code as you have it at the moment is pretty susceptible to SQL injection attack:

   callback(`${fromAndTo}${obj.to}\', \'${obj.from}\')`);

You're placing values directly from the post data into the SQL call with no escaping or validation.

**Comment by RobStallion** [comment]
We'll have a go at refactoring this but it will probably be later on this week. Looks like we should be able to implement it based on the above.
