### ISSUE TITLE
Overview architectural diagram in wiki

### ISSUE THREAD

**Issue by peterw8102** [ipcortex/FAC-FMC#153]
showing the components, how they talk to each other then a text list referencing the source tree.

**Comment by RobStallion** [comment]
Do you want us to make a wiki for this?

**Comment by peterw8102** [comment]
A page in the wiki I think. Nothing too complicated. If someone is trying to understand your code at the top level you need to know which blocks exists, how they relate to one another and where to find those blocks in the source tree.

**Comment by RobStallion** [comment]
Ok we will get on that. Could be a good exercise for when Ellie is back so that she we can go through the code with her at the same time and get her up to speed.

**Comment by peterw8102** [comment]
Good idea. Always a good sanity check having to explain what you've done to someone else :-)
