### ISSUE TITLE
JWT usage and passwords.

### ISSUE THREAD

**Issue by peterw8102** [ipcortex/FAC-FMC#155]
Just checking how JWT works. The payload isn't encrypted it's just base64 encoded with a signature to make sure it's not been tampered with. This means all the data in the payload *could* be vulnerable to attack. As such I don't think it's a good idea to store anything that's not absolutely required in the token.

In particular it looks like you store the password in the JWT - which seems somewhat risky.

**Comment by RobStallion** [comment]
We will take the password out of the JWT and have a look to see if there is anything else that we is in it that we could do without.
