### ISSUE TITLE
SQL to filter calls

### ISSUE THREAD

**Issue by peterw8102** [ipcortex/FAC-FMC#156]
Just recording this before I forget. The SQL to read call records that involve a specific participant:

    SELECT c.*, 
       p1.participant_id AS caller_id, p1.internal AS caller_internal, p1.number AS caller_number, p1.contact_id AS caller_contact, 
       p2.participant_id AS called_id, p2.internal AS called_internal, p2.number AS called_number, p2.contact_id AS caller_contact
    FROM calls c 
        LEFT JOIN participants p1 ON c.call_id = p1.call_id AND p1.participant_role = 'callee'
        LEFT JOIN participants p2 ON c.call_id = p2.call_id AND p2.participant_role = 'caller'
    WHERE c.call_id IN (SELECT p.call_id FROM participants p WHERE p.contact_id=_contactID_)
        AND _other conditions_;

**Comment by RobStallion** [comment]
Hi pete, so we've been experimenting with the new SQL and want to return all untagged calls with:

```
SELECT c.*,
   p1.participant_id AS caller_id, p1.internal AS caller_internal, p1.number AS caller_number, p1.contact_id AS caller_contact,
   p2.participant_id AS callee_id, p2.internal AS callee_internal, p2.number AS callee_number, p2.contact_id AS callee_contact,
   array(select t.tag_name from tags t where t.tag_id in (select tc.tag_id from tags_calls tc where tc.call_id = c.call_id)) as tag_name
FROM calls c
    LEFT JOIN participants p1 ON c.call_id = p1.call_id AND p1.participant_role = 'caller'
    LEFT JOIN participants p2 ON c.call_id = p2.call_id AND p2.participant_role = 'callee'
WHERE ..........(Unknown code to filter by array )
```

We have managed to filter by all other columns in the newly created table except for the tag_name column and cannot seem to find the solution online. Any help would be greatly appreciated

**Comment by peterw8102** [comment]
I think the missing condition will be something like:

WHERE NOT EXISTS (SELECT 1 FROM tags_calls tc WHERE tc.call_id = c.vall_id)

I can check that tomorrow - don't have a suitable database here!

**Comment by RobStallion** [comment]
That's perfect Pete. Thanks a lot again.
