### ISSUE TITLE
Calls should get deleted after 21 days to preserve the limited storage space

### ISSUE THREAD

**Issue by Virginie-T** [ipcortex/FAC-FMC#17]

**Comment by rjp44** [comment]
21 days is the current default that files are stored on the IPCortex appliance. The intention is that the call recording server will store them for (much) longer than this. The expiry requirement for the MVP project is therefore:

1. No expiry policy, functionality is missing, to be implemented later
or

2. Have a configurable expiry time period (configurable by admin only, not end user). Stretch goal, definitely not core MVP functionality.
