### ISSUE TITLE
api rest/call/list response 

### ISSUE THREAD

**Issue by eleanorreem** [ipcortex/FAC-FMC#171]
When polling for company calls for default and testcompany we get the response : 
We are certain this code worked previously.
{ result: 'fail',   message: 'cannot access files. perhaps there are none?' }

**Comment by RobStallion** [comment]
When we make an api call to /rest/auth with the api key given to us this is the response we get...
```
{ result: 'success',
  user:
   { id: 682,
     login: 'fmc-polling2',
     name: 'FMC Polling',
     company: 'default',
     home: 'testcompany',
     companies: [ 'default', 'testcompany' ],
     session: 'UgUSM7RlZL3o0lbv9JkzAGZd',
     perms: { comp: 'company', callrec_dl: 'yes' } } }
```

We are using these companies in the above and getting the error

**Comment by davies147** [comment]
Curious - The PABX was upgraded recently, which is the likely cause - I'll look at this now.

**Comment by davies147** [comment]
*PHEW* This is a more obvious issue that I realised. The last call was call recorded on 2016.06.15, which is more than 21 days ago - All of your call recordings have now expired, so "cannot access files. perhaps there are none?" is pretty accurate.

**Comment by RobStallion** [comment]
Ok that makes perfect sense haha. We are trying to test our poller flow now though so would it be possible to add some dummy calls to 'default' and 'testcompany'?

**Comment by bengesoff** [comment]
It _would_ be possible if you opened [keevio](https://fac1.ipcortex.net/keevio/) in two different places and called each other a few times :smile:

**Comment by RobStallion** [comment]
Genius. Thanks
