### ISSUE TITLE
In general, how do we want to deal with error handling?

### ISSUE THREAD

**Issue by eleanorreem** [ipcortex/FAC-FMC#254]
I'm assuming we don't want to throw errors?

**Comment by peterw8102** [comment]
For the poller it may be OK to throw an error and cause the application to abort although logging the error may be a good idea. Assuming most errors should be transient, such as database not running or network down, then the next poll should work and everything should get in sync.

For the UI, exceptions shouldn't be thrown unless they are caught higher up the stack and dealt with in a reasonably sane way.
