### ISSUE TITLE
Schema Design

### ISSUE THREAD

**Issue by tu6619** [ipcortex/FAC-FMC#26]
Consensus on a primary schema needed in order for work on client side and polling servers to begin.

**Comment by peterw8102** [comment]
Example schema:

[schema.txt](https://github.com/ipcortex/FAC-FMC/files/305088/schema.txt)

**Comment by tu6619** [comment]
[schema-quests.txt](https://github.com/ipcortex/FAC-FMC/files/307047/schema-quests.txt)

**Comment by tu6619** [comment]
These are a list of questions we had about the example schema.

**Comment by peterw8102** [comment]
Quick answers:
1. fields for the file table. probably just the unique ID and file name (basically where' the actual audio file is saved). It's better to use an integer as a unique identified for the recording than the long file name. Faster to access and join against.

2. The constraint is on the 'call' table but the ON DELETE CASCADE refers to the referenced table (files). So if a row in the files table is deleted all referencing rows in the call table are deleted. You might want 'ON DELETE RESTRICT' so you prevent any 'file' rows being deleted if there are any referring call records.
3. 'sequences' in Postgres are simply a way of generating a stream of numbers. The order can be modified and there can be gaps. You can explicitly set the value of the ID column to any value you want - uniqueness is not enforced. The unique index enforces that [company_id,tag_id] must be unique.

4. Postgres is quite good at using partial keys. There are potentially many operations you'll need to do that are scoped by company (show me all the tags that belong to this company, if a company is deleted then delete all the referenced tags/calls/participants). So by making the unique key [company_id, tag], Postgres can use the key to find "all things that belong to company X".

**Comment by tu6619** [comment]
- Regarding the files table, are you saying we actually don't need a file_index field as file_id would be the unique identifier with which we would retrieve files upon request?
- Please find our schema so far attached. We've included a mixture of ON DELETE RESTRICT and ON DELETE CASCADE erring on the side of caution. Let us know what you think. 
- The 'ADD DUMMY DATA' field is still incomplete, we still need to figure out how the database will be populated from the data returned by the poller. 
[fmc-schema.txt](https://github.com/ipcortex/FAC-FMC/files/307458/fmc-schema.txt)

**Comment by peterw8102** [comment]
I think file_id is the unique (numeric) ID for each file and file_index isn't needed.

Sorry - I posted my other comments in the IM but they'd actually be more useful here!

**Comment by eleanorreem** [comment]
[db_schema.txt](https://github.com/ipcortex/FAC-FMC/files/309073/db_schema.txt)
This is the new schema

**Comment by Virginie-T** [comment]
Steve Davies :             
I do like the simplification of calls having a PK of just call_id - much cleaner.              
It may be necessary to search on files.file_name in order to check for duplicates before downloading a file, so you probably want to CREATE UNIQUE INDEX ON files(file_name);

**Comment by Virginie-T** [comment]
Peter Wilson :               
Except that on of the key filters on 'calls' will be the company they belong to - so to me having the company_id part of the key makes more sense? So I never want to see all calls in the roles we have. It will always be SELECT xxx FROM calls WHERE company_id=1234 AND (other things)
file_index might be useful in future although presumably initially the files will be stored in the local file system with the same name as that given by the PABX

**Comment by Virginie-T** [comment]
Steve Davies : 
I am reserving judgement on the use of company as I am not confident that I understand how it is being used well enough to comment fully. Looking at the schema, either call_id or call_id + company_id could be valid depending on the most common use-case and whether it is useful to limit the data in that manner or not.
I agree that file_indexis probably redundant.
The local filename could be the same as file_name or it could be 'recording_' + file_id

**Comment by Virginie-T** [comment]
Peter Wilson : 
In the 'users' table you probably don't need to store the role. That should be calculated each time the user is authenticated with the PABX, which covers them becoming an admin or loosing that permission.
