### ISSUE TITLE
As a client I want to be able to log in

### ISSUE THREAD

**Issue by eleanorreem** [ipcortex/FAC-FMC#4]

**Comment by bengesoff** [comment]
Would the default IPCortex API suffice for this?
http://developer.ipcortex.co.uk/gs/js/authentication/#auto-authentication-via--pop-up-

**Comment by bengesoff** [comment]
The spec says they should log in with a PBX login so it might be more convenient to let them log in with the popup, then get the current username from the API with
http://developer.ipcortex.co.uk/ref/js/properties/auth/#menu-ipcortex-pbx-auth-uname
And use that for authentication with the FMC server

**Comment by bengesoff** [comment]
I just realised that's stupid, sorry, ignore me! (I think) the client side shouldn't have access to the IPCortex API so the logins should be passed through the server
