### ISSUE TITLE
Authentication details for a dummy company? Or the FAC company we used before? 

### ISSUE THREAD

**Issue by eleanorreem** [ipcortex/FAC-FMC#47]
Is there any way we can get auth details so that we can grab dummy data from a company?

**Comment by rjp44** [comment]
Your inidividual FAC logins on fac1.ipcortex.net from the webrtc project should still work, but that is a single company box and you will always get 'default' back as the company_id (which is fine). We can setup some credentials on a box with more than one company if you need them for testing, but you should be able to get going with the above.
