### ISSUE TITLE
Issue with the /rest/dialplan/read/

### ISSUE THREAD

**Issue by eleanorreem** [ipcortex/FAC-FMC#82]
extension list is [ '241', 'webrtc674', '238', '239' ]

request
``` javascript
const retrieveCallerDetails = (company_name, extensionList, callback) => {
  const options = {
    url: pbxUrl + '/rest/dialplan/read',
    encoding: null,
    headers: {
      'cache-control': 'no-cache',
      'content-type': 'application/json'
    },
    body: {
      type: 'extension',
      scope: {     // eg "400"
        'virt_exten': extensionList,    // eg "400_company",
        'company': company_name,
      },
      auth: {
        type: 'auth',
        key: apiKey
      },
      columns: [
        'virt_exten',
        'company',
        'scoped_exten',
        'owner'
      ]
    },
    json: true
  }
  request(options, function (error, response, body) {
    if (error) throw error
    callback(body)
  })
}

``` 

response 

``` javascript

{ result: 'fail', message: 'Illegal request dialplan/read/' }

```

**Comment by bengesoff** [comment]
The problem is with the `webrtc674` extension, second in the array: it is not a valid extension. However, it shouldn't actually _fail_ so Stevo will take a look after lunch. For now, if you need it to work before it's fixed, just make sure that extension is filtered out before making the request.

**Comment by bengesoff** [comment]
The reason that the extension is there, is that we made a call with a semi-configured user while testing the call recording and it can be considered an edge case, so don't worry about it.

**Comment by eleanorreem** [comment]
Hi Ben, I've filtered it out but I'm getting the same message. Is there something wrong in the request object?

``` javascript 
extension list...
[ '241', '238', '239' ]

response ...
{ result: 'fail', message: 'Illegal request dialplan/read/' }

```

**Comment by bengesoff** [comment]
Stevo is just taking a look, we'll update you when he's found it :smiley_cat:

**Comment by davies147** [comment]
Could you try again to see if you get a different result now? I have added a missing library dependency, but that should not have caused this particular issue...

**Comment by davies147** [comment]
I believe you should now get "not authenticated" which I will fix in a moment.

**Comment by davies147** [comment]
I've now added permissions and get a "good" result here for your query.

**Comment by eleanorreem** [comment]
Thanks. 

I'm now getting:

``` javascript
 
{ result: 'fail',
  message: 'Illegal request dialplan/read/',
  post: '',
  data: { type: '' } }

```

**Comment by eleanorreem** [comment]
perhaps the api key that I have doesnt have the right authentication

**Comment by davies147** [comment]
Are you sure you are doing a POST request and not a GET request? The POST body is empty?

**Comment by eleanorreem** [comment]
You hit the nail on the head. thanks!

**Comment by davies147** [comment]
I did find a bug anyway, so it was "worth it" :)

**Comment by eleanorreem** [comment]
Yeah sorry, very silly mistake.

**Comment by davies147** [comment]
No, I mean I found a bug in the server also :)

**Comment by RobStallion** [comment]
So we are currently sending a request to the api with the following array of callers, 
[ 'webrtc674', '239', '238' ]

and this is the response that it gives us 
{ result: 'success', values: [] }

I am wondering if perhaps we were doing something slightly wrong still or if there is just no data for these callers

I have attached a picture of the request as well for you to have a look at in case there is an error there

![screen shot 2016-06-20 at 15 43 19](https://cloud.githubusercontent.com/assets/15571853/16198430/cfbbfa44-36fd-11e6-973e-a608ab0e5647.png)

**Comment by davies147** [comment]
Emailing this response. Hope it works!

What are you setting 'company' to in your example?

**Comment by RobStallion** [comment]
the company that we are polling is 'default'

**Comment by davies147** [comment]
(just got out of a loooong meeting) OK, I will try this from here.
Could you let me know the first 3 characters of the API key you are using so I can replicate that.

**Comment by RobStallion** [comment]
No problem. I wasn't sure if it was an email issue is all. 

The first 3 letters are 'tyw'

**Comment by davies147** [comment]
OK, The user associated with that key had not been granted admin rights over any companies, and could not therefore read from the extensions list.

I have added the correct admin rights to that user and it now seems to work for me.

**Comment by RobStallion** [comment]
That is amazing. Worked first time. Thanks
